import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { motion } from 'motion/react';
import { 
  Play, Pause, SkipForward, SkipBack, 
  Activity, Radio, Zap, Sparkles,
  RefreshCw, Headphones, Mic2, FileText
} from 'lucide-react';

interface Voice {
  id: string;
  name: string;
  lang: string;
  dialect: string;
  gender: 'M' | 'F';
  langCode: string;
}

const VOICES: Voice[] = [
  { id: 'tn-01', name: 'Zied', lang: 'Arabic', dialect: 'Tunisian', gender: 'M', langCode: 'ar-TN' },
  { id: 'tn-02', name: 'Leila', lang: 'Arabic', dialect: 'Tunisian', gender: 'F', langCode: 'ar-TN' },
  { id: 'fr-01', name: 'Julien', lang: 'French', dialect: 'Standard', gender: 'M', langCode: 'fr-FR' },
  { id: 'en-01', name: 'Sarah', lang: 'English', dialect: 'Neutral', gender: 'F', langCode: 'en-US' },
];

const BRIEFING_TEXT = `Good morning. This is your daily strategic intelligence briefing for {date}. 
The Revolutionary Risk Index currently stands at 2.31, indicating elevated systemic pressure with a probability of regime change estimated at 64.3 percent over the next twelve months.
Key economic indicators show inflation at 7.1 percent, foreign exchange reserves covering 84 days of imports, and unemployment at 16.4 percent nationally.
On the social front, protest activity remains elevated with 23 events recorded in the past 30 days. Water stress continues to affect 8 governorates.
Geopolitically, the IMF deal probability stands at 31 percent, while the EU partnership status remains strained.
Agricultural intelligence reports moderate stress across the cereal belt, with groundwater depletion accelerating in the southern governorates.
This briefing was generated by the TunisiaIntel sovereign risk intelligence engine. Stay vigilant.`;

const getTodaysBriefing = () => {
  const d = new Date();
  const dateStr = d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  return BRIEFING_TEXT.replace('{date}', dateStr);
};

// Stable pseudo-random heights for waveform bars (avoid Math.random flicker)
const WAVE_BARS = Array.from({ length: 40 }, (_, i) => ({
  key: i,
  base: ((i * 17 + 31) % 60) + 20,
}));

const CURSOR = '\u2588';

export const AIVoiceBriefing: React.FC = () => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [selectedVoice, setSelectedVoice] = useState(VOICES[0]);
  const [progress, setProgress] = useState(0);
  const [isSynthesizing, setIsSynthesizing] = useState(false);
  const [revealedChars, setRevealedChars] = useState(0);
  const [status, setStatus] = useState<'READY' | 'SYNTHESIZING' | 'PLAYING'>('READY');
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);
  const progressIntervalRef = useRef<any>(null);
  const typewriterRef = useRef<any>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const briefingText = useMemo(() => getTodaysBriefing(), []);
  const totalDuration = useMemo(() => Math.ceil(briefingText.split(' ').length * 350 / 1000), [briefingText]);
  const revealedRef = useRef(0);

  // Auto-scroll transcript as text reveals
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [revealedChars]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      window.speechSynthesis.cancel();
      if (progressIntervalRef.current) clearInterval(progressIntervalRef.current);
      if (typewriterRef.current) clearInterval(typewriterRef.current);
    };
  }, []);

  const startTypewriter = useCallback(() => {
    const totalChars = briefingText.length;
    const msPerChar = (totalDuration * 1000) / totalChars;
    if (typewriterRef.current) clearInterval(typewriterRef.current);
    typewriterRef.current = setInterval(() => {
      setRevealedChars(prev => {
        const next = prev + 1;
        revealedRef.current = next;
        if (next >= totalChars) {
          if (typewriterRef.current) clearInterval(typewriterRef.current);
          return totalChars;
        }
        return next;
      });
    }, msPerChar);
  }, [briefingText, totalDuration]);

  const stopTypewriter = useCallback(() => {
    if (typewriterRef.current) {
      clearInterval(typewriterRef.current);
      typewriterRef.current = null;
    }
  }, []);

  const startProgress = () => {
    const words = briefingText.split(' ').length;
    const estimatedMs = words * 350;
    const step = 100 / (estimatedMs / 100);
    if (progressIntervalRef.current) clearInterval(progressIntervalRef.current);
    progressIntervalRef.current = setInterval(() => {
      setProgress(p => Math.min(p + step, 99));
    }, 100);
  };

  const stopProgress = () => {
    if (progressIntervalRef.current) {
      clearInterval(progressIntervalRef.current);
      progressIntervalRef.current = null;
    }
  };

  const handleTogglePlay = () => {
    if (status === 'READY') {
      setIsSynthesizing(true);
      setStatus('SYNTHESIZING');

      setTimeout(() => {
        setIsSynthesizing(false);
        const utterance = new SpeechSynthesisUtterance(briefingText);
        utterance.lang = selectedVoice.langCode;
        utterance.rate = 0.85;
        utterance.pitch = selectedVoice.gender === 'M' ? 0.9 : 1.1;

        const voices = window.speechSynthesis.getVoices();
        const match = voices.find(v => v.lang.startsWith(selectedVoice.langCode));
        if (match) utterance.voice = match;

        utterance.onstart = () => {
          setIsPlaying(true);
          setStatus('PLAYING');
          startProgress();
          startTypewriter();
        };

        utterance.onend = () => {
          setIsPlaying(false);
          setStatus('READY');
          setRevealedChars(briefingText.length);
          setProgress(100);
          stopProgress();
          stopTypewriter();
        };

        utterance.onerror = () => {
          setIsPlaying(false);
          setStatus('READY');
          setProgress(0);
          stopProgress();
          stopTypewriter();
        };

        utteranceRef.current = utterance;
        window.speechSynthesis.cancel();
        window.speechSynthesis.speak(utterance);
      }, 600);
    } else if (isPlaying) {
      window.speechSynthesis.pause();
      setIsPlaying(false);
      stopProgress();
      stopTypewriter();
    } else {
      window.speechSynthesis.resume();
      setIsPlaying(true);
      startProgress();
      startTypewriter();
    }
  };

  const handleReset = () => {
    window.speechSynthesis.cancel();
    setIsPlaying(false);
    setProgress(0);
    setRevealedChars(0);
    revealedRef.current = 0;
    setStatus('READY');
    stopProgress();
    stopTypewriter();
  };

  const revealedText = briefingText.slice(0, revealedChars);

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      {/* ── MAIN PLAYER + TRANSCRIPT ── */}
      <div className="glass p-8 md:p-12 rounded-[2.5rem] border border-intel-border/30 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-intel-cyan/5 via-transparent to-purple-500/5 pointer-events-none" />
        <div className="absolute top-0 right-0 w-96 h-96 bg-intel-cyan/5 blur-[100px] rounded-full -mr-48 -mt-48" />

        <div className="relative z-10 flex flex-col items-center space-y-8">
          {/* Header */}
          <div className="text-center space-y-2">
            <div className="flex items-center justify-center gap-2 text-[10px] font-bold text-intel-cyan font-mono uppercase tracking-[0.3em]">
              <div className="w-1.5 h-1.5 bg-intel-cyan rounded-full animate-pulse" />
              Neural Intelligence Synthesis
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-white tracking-tight">Daily Strategic Narrative</h2>
            <p className="text-slate-400 text-sm max-w-md mx-auto">
              Strategic briefing for {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long' })}.
            </p>
          </div>

          {/* Waveform Visualizer */}
          <div className="w-full h-24 flex items-center justify-center gap-1">
            {WAVE_BARS.map((bar) => (
              <motion.div
                key={bar.key}
                animate={{
                  height: isPlaying ? [bar.base, bar.base + 30, bar.base] : 4,
                  opacity: isPlaying ? [0.4, 1, 0.4] : 0.15,
                }}
                transition={{
                  duration: 0.8 + (bar.key % 3) * 0.15,
                  repeat: Infinity,
                  delay: bar.key * 0.04,
                  ease: "easeInOut"
                }}
                className={`w-1 rounded-full ${bar.key % 2 === 0 ? 'bg-intel-cyan' : 'bg-purple-500'}`}
              />
            ))}
          </div>

          {/* Transcript Panel */}
          <div className="w-full max-w-3xl">
            <div className="flex items-center gap-2 mb-2">
              <FileText className="w-3.5 h-3.5 text-intel-cyan" />
              <span className="text-[9px] font-mono text-slate-500 uppercase tracking-widest">Transcript Feed</span>
              {isPlaying && (
                <span className="text-[8px] font-mono text-green-400 animate-pulse ml-auto">LIVE</span>
              )}
            </div>
            <div
              ref={scrollRef}
              className="h-48 overflow-y-auto bg-[#0a0c10] border border-intel-cyan/10 rounded-xl p-5 font-mono text-[12px] leading-relaxed scrollbar-thin scrollbar-thumb-intel-cyan/10"
              style={{ boxShadow: 'inset 0 0 30px rgba(0,242,255,0.03)' }}
            >
              {revealedChars === 0 && status === 'READY' ? (
                <span className="text-slate-700 italic">Awaiting transmission...</span>
              ) : (
                <>
                  <span className="text-intel-cyan/90">
                    {revealedText}
                  </span>
                  {revealedChars < briefingText.length ? (
                    <span className="text-intel-cyan animate-pulse">{CURSOR}</span>
                  ) : (
                    <span className="text-green-400 ml-1">[TRANSMISSION_COMPLETE]</span>
                  )}
                </>
              )}
            </div>
          </div>

          {/* Player Controls */}
          <div className="flex flex-col items-center space-y-6 w-full max-w-xl">
            <div className="w-full space-y-2">
              <div className="flex justify-between text-[10px] font-mono text-slate-500 uppercase">
                <span>{Math.floor(progress / 100 * totalDuration)}s</span>
                <span>{totalDuration}s</span>
              </div>
              <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden border border-white/5">
                <motion.div
                  className="h-full bg-gradient-to-r from-intel-cyan to-purple-500"
                  initial={{ width: 0 }}
                  animate={{ width: `${progress}%` }}
                />
              </div>
            </div>

            <div className="flex items-center gap-8">
              <button className="p-3 text-slate-500 hover:text-white transition-colors" disabled>
                <SkipBack className="w-6 h-6 opacity-30" />
              </button>

              <button
                onClick={handleTogglePlay}
                disabled={isSynthesizing}
                className={`w-20 h-20 rounded-full flex items-center justify-center transition-all transform hover:scale-110 shadow-2xl ${
                  status === 'SYNTHESIZING'
                    ? 'bg-slate-800 animate-pulse cursor-wait'
                    : 'bg-white text-black'
                }`}
              >
                {isSynthesizing ? (
                  <RefreshCw className="w-8 h-8 animate-spin" />
                ) : isPlaying ? (
                  <Pause className="w-8 h-8" fill="currentColor" />
                ) : (
                  <Play className="w-8 h-8 ml-1" fill="currentColor" />
                )}
              </button>

              <button className="p-3 text-slate-500 hover:text-white transition-colors" disabled>
                <SkipForward className="w-6 h-6 opacity-30" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* ── SETTINGS & VOICES ── */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 glass p-6 rounded-3xl border border-white/5 space-y-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-intel-cyan/10 rounded-xl">
                <Mic2 className="w-4 h-4 text-intel-cyan" />
              </div>
              <h3 className="text-xs font-bold text-white uppercase tracking-widest">Voice Engine</h3>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {VOICES.map((v) => (
              <button
                key={v.id}
                onClick={() => setSelectedVoice(v)}
                className={`p-4 rounded-2xl border text-left transition-all space-y-1 relative group overflow-hidden ${
                  selectedVoice.id === v.id
                    ? 'bg-intel-cyan/10 border-intel-cyan/50'
                    : 'bg-white/5 border-white/5 hover:border-white/20'
                }`}
              >
                {selectedVoice.id === v.id && (
                  <div className="absolute top-0 right-0 p-1.5">
                    <Sparkles className="w-3 h-3 text-intel-cyan" />
                  </div>
                )}
                <div className="text-[10px] font-bold text-white">{v.name}</div>
                <div className="text-[8px] text-slate-500 uppercase tracking-tighter">{v.lang}</div>
                <div className="text-[8px] font-mono text-intel-cyan opacity-60">{v.dialect}</div>
              </button>
            ))}
          </div>
        </div>

        <div className="glass p-6 rounded-3xl border border-white/5 flex flex-col justify-between">
          <div className="space-y-4">
            <h3 className="text-xs font-bold text-white uppercase tracking-widest">Actions</h3>
            <div className="space-y-2">
              <button
                onClick={handleReset}
                className="w-full flex items-center justify-between p-3 bg-white/5 hover:bg-white/10 rounded-xl border border-white/5 transition-all group"
              >
                <div className="flex items-center gap-2 text-[10px] font-mono text-slate-300">
                  <RefreshCw className="w-3 h-3 group-hover:text-intel-cyan" />
                  <span>Regenerate</span>
                </div>
                <Activity className="w-3 h-3 text-slate-600" />
              </button>
            </div>
          </div>

          <div className="p-3 bg-intel-cyan/5 border border-intel-cyan/20 rounded-xl mt-4">
            <div className="flex items-center gap-2 text-[8px] font-bold text-intel-cyan uppercase tracking-widest mb-1">
              <Radio className="w-2.5 h-2.5 animate-pulse" />
              Channel 1
            </div>
            <p className="text-[9px] text-slate-500 leading-tight">
              Browser speech synthesis via Web Speech API.
            </p>
          </div>
        </div>
      </div>

      {/* ── STATUS ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: 'Synthesis', value: selectedVoice.lang, icon: Zap, status: 'OK' },
          { label: 'Dialect', value: selectedVoice.dialect, icon: Activity, status: 'OK' },
          { label: 'Duration', value: `${totalDuration}s`, icon: FileText, status: 'OK' },
          { label: 'Characters', value: `${revealedChars}/${briefingText.length}`, icon: Headphones, status: revealedChars === briefingText.length ? 'DONE' : 'OK' },
        ].map((s, i) => (
          <div key={i} className="glass p-4 rounded-2xl border border-white/5 flex items-center gap-4">
            <div className="p-2 bg-white/5 rounded-lg">
              <s.icon className="w-3.5 h-3.5 text-slate-400" />
            </div>
            <div className="space-y-0.5">
              <div className="text-[8px] font-mono text-slate-500 uppercase tracking-widest">{s.label}</div>
              <div className="text-[10px] font-bold text-white font-mono">{s.value}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default AIVoiceBriefing;
