from .models import Entity, Relation

# ── Geopolitical Actors (from GeopoliticalNetworkGraph.tsx) ──────────

GEOPOLITICAL_ENTITIES: list[Entity] = [
    Entity(id="TUN", type="actor", label="Tunisia", tier=1, domain=["energy","migration","security","finance","infrastructure","diplomatic","ideological","strategic"], power_type="soft",
           resources={"economic":3,"military":2,"diplomatic":4,"informational":3}, color="#00f2ff", size=50,
           goals=["IMF agreement","EU partnership","Security stability"], constraints=["Debt trap","Youth unemployment","Regional instability"],
           risk_tolerance="medium", time_horizon="medium", fixed_x=0, fixed_y=0),
    Entity(id="DZA", type="actor", label="Algeria", tier=2, domain=["energy","security","diplomatic"], power_type="hard",
           resources={"economic":5,"military":7,"diplomatic":6,"informational":4}, color="#10b981", size=30,
           goals=["Regional influence","Counter Morocco","Energy exports"], constraints=["Oil dependency","Internal stability","Legitimacy"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="ITA", type="actor", label="Italy", tier=2, domain=["migration","energy","diplomatic"], power_type="hard",
           resources={"economic":7,"military":6,"diplomatic":7,"informational":7}, color="#3b82f6", size=30,
           goals=["Migration control","Energy diversification","Mediterranean influence"], constraints=["EU constraints","Domestic politics"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="FRA", type="actor", label="France", tier=2, domain=["security","finance","diplomatic","ideological"], power_type="soft",
           resources={"economic":8,"military":8,"diplomatic":9,"informational":8}, color="#6366f1", size=30,
           goals=["Neocolonial influence","Counter China","IMF alignment"], constraints=["Post-colonial resentment","EU bureaucracy"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="EU", type="institution", label="European Union", tier=2, domain=["finance","diplomatic","ideological","strategic"], power_type="structural",
           resources={"economic":9,"military":9,"diplomatic":10,"informational":9}, color="#a855f7", size=30,
           goals=["Southern neighborhood stability","Migration management","Rule of law promotion"], constraints=["Consensus requirement","Visegrad resistance"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="USA", type="actor", label="United States", tier=2, domain=["security","finance","strategic"], power_type="hard",
           resources={"economic":9,"military":10,"diplomatic":8,"informational":8}, color="#E36C0A", size=50,
           goals=["NATO southern flank","Counter Russia/China","IMF alignment"], constraints=["Indo-Pacific pivot","Congressional gridlock"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="KSA", type="actor", label="Saudi Arabia", tier=3, domain=["finance","ideological","strategic"], power_type="extractive",
           resources={"economic":7,"military":5,"diplomatic":5,"informational":4}, color="#10b981", size=20,
           goals=["Vision 2030 investment","Counter Iran","Energy market share"], constraints=["Vision 2030 timeline","Regional rivalry"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="UAE", type="actor", label="United Arab Emirates", tier=3, domain=["finance","strategic","diplomatic"], power_type="extractive",
           resources={"economic":7,"military":4,"diplomatic":6,"informational":5}, color="#f59e0b", size=20,
           goals=["Port/finance expansion","Counter Islamism","Gulf leadership"], constraints=["Small population","Regional perception"],
           risk_tolerance="high", time_horizon="long"),
    Entity(id="CHN", type="actor", label="China", tier=3, domain=["finance","infrastructure","strategic"], power_type="structural",
           resources={"economic":10,"military":9,"diplomatic":7,"informational":6}, color="#ef4444", size=20,
           goals=["Belt & Road expansion","Resource access","Debt diplomacy"], constraints=["Geographic distance","EU scrutiny"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="GBR", type="actor", label="United Kingdom", tier=3, domain=["finance","diplomatic","strategic"], power_type="soft",
           resources={"economic":7,"military":6,"diplomatic":5,"informational":6}, color="#14b8a6", size=20,
           goals=["Post-Brexit trade","Security partnerships","Africa engagement"], constraints=["Post-Brexit bandwidth","Economic constraints"],
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="TUR", type="actor", label="Turkey", tier=3, domain=["security","diplomatic","ideological","strategic"], power_type="hard",
           resources={"economic":6,"military":7,"diplomatic":6,"informational":5}, color="#f97316", size=20,
           goals=["Africa expansion","Counter PKK/PYD","Drone exports"], constraints=["Economic crisis","Regional overextension"],
           risk_tolerance="high", time_horizon="medium"),
    Entity(id="QAT", type="actor", label="Qatar", tier=3, domain=["finance","diplomatic","ideological"], power_type="extractive",
           resources={"economic":6,"military":2,"diplomatic":7,"informational":7}, color="#ec4899", size=20,
           goals=["Mediation role","LNG exports","Soft power projection"], constraints=["Blockade trauma","Regional alignment"],
           risk_tolerance="high", time_horizon="short"),
    Entity(id="RUS", type="actor", label="Russia", tier=4, domain=["security","ideological","strategic"], power_type="hard",
           resources={"economic":5,"military":9,"diplomatic":6,"informational":7}, color="#dc2626", size=15,
           goals=["Counter NATO","Influence in Africa","Wagner/PMC network"], constraints=["Ukraine war","Sanctions"],
           risk_tolerance="high", time_horizon="long"),
    Entity(id="LBY", type="actor", label="Libya", tier=4, domain=["migration","security","energy"], power_type="hard",
           resources={"economic":3,"military":4,"diplomatic":2,"informational":2}, color="#78716c", size=15,
           goals=["Stabilization","Resource control","Border management"], constraints=["Civil war","Militia fragmentation"],
           risk_tolerance="high", time_horizon="short"),
]

GEOPOLITICAL_RELATIONS: list[Relation] = [
    Relation(id="geopol-1", source_id="TUN", target_id="DZA", type="cooperative", weight=6, domain="energy", conditionality="Unstable", trend="declining",
             description="Algeria supplies 60% of Tunisia's natural gas via ENI pipeline."),
    Relation(id="geopol-2", source_id="TUN", target_id="FRA", type="dependent", weight=8, domain="finance", conditionality="Conditional", trend="declining",
             description="France is Tunisia's 2nd largest trade partner and holds significant debt leverage."),
    Relation(id="geopol-3", source_id="TUN", target_id="EU", type="cooperative", weight=4, domain="diplomatic", conditionality="Partial", trend="declining",
             description="EU-Tunisia association agreement provides trade framework and aid."),
    Relation(id="geopol-4", source_id="TUN", target_id="USA", type="cooperative", weight=3, domain="security", conditionality="Limited", trend="stable",
             description="USA provides counter-terrorism training and equipment. Limited financial leverage."),
    Relation(id="geopol-5", source_id="TUN", target_id="KSA", type="dependent", weight=5, domain="finance", conditionality="At risk", trend="declining",
             description="Saudi aid package (2018) through Saudi Fund for Development."),
    Relation(id="geopol-6", source_id="TUN", target_id="UAE", type="cooperative", weight=4, domain="finance", conditionality="Stable", trend="stable",
             description="UAE investments in Tunisian banking and infrastructure."),
    Relation(id="geopol-7", source_id="TUN", target_id="CHN", type="cooperative", weight=3, domain="infrastructure", conditionality="Emerging", trend="rising",
             description="Growing Chinese presence through BRI projects in infrastructure and technology."),
    Relation(id="geopol-8", source_id="TUN", target_id="RUS", type="cooperative", weight=1, domain="diplomatic", conditionality="Minimal", trend="stable",
             description="Limited diplomatic engagement. Some arms deals historically."),
    Relation(id="geopol-9", source_id="TUN", target_id="DZA", type="coercive", weight=3, domain="security", conditionality="Strategic buffer", trend="stable",
             description="Algeria controls Tunisia's western border. Security coordination but also pressure via border closures."),
    Relation(id="geopol-10", source_id="TUN", target_id="LBY", type="spillover", weight=8, domain="migration", conditionality="Uncontrolled", trend="rising",
             description="Libyan civil war creates migration waves and arms smuggling into Tunisia."),
    Relation(id="geopol-11", source_id="TUN", target_id="LBY", type="competitive", weight=5, domain="strategic", conditionality="Unstable", trend="rising",
             description="Competition over energy resources in the Gulf of Gabes and border stability."),
    Relation(id="geopol-12", source_id="ITA", target_id="TUN", type="coercive", weight=8, domain="migration", conditionality="Conditional", trend="stable",
             description="Italy pressures Tunisia to accept deportations and patrol Mediterranean waters."),
    Relation(id="geopol-13", source_id="FRA", target_id="TUN", type="coercive", weight=5, domain="finance", conditionality="Conditional", trend="declining",
             description="France conditions aid and investment on political reforms and IMF compliance."),
    Relation(id="geopol-14", source_id="QAT", target_id="TUN", type="extractive", weight=3, domain="infrastructure", conditionality="Negotiable", trend="stable",
             description="Qatar provides investment in Tunisian infrastructure and renewable energy projects."),
]

# ── National Actors (from NationalActorNetwork.tsx) ──────────

NATIONAL_ENTITIES: list[Entity] = [
    Entity(id="PRES", type="actor", label="Presidency / Palace", tier=1, domain=["constitutional_power","political_repression","narrative_warfare","electoral_politics"],
           power_type="institutional", resources={"popular":3,"institutional":9,"economic":6,"informational":7}, color="#ef4444", size=55,
           goals=["Control security apparatus","Maintain elite cohesion","Neutralize opposition"], constraints=["UGTT veto","BCT limits","ENN resistance"],
           risk_tolerance="high", time_horizon="short", aliases=["Presidency", "Palace", "Kaïs Saïed"]),
    Entity(id="UGTT", type="institution", label="UGTT", tier=2, domain=["social_dialogue","labor_organization","protest_coordination"],
           power_type="mobilizational", resources={"popular":9,"institutional":7,"economic":3,"informational":6}, color="#f59e0b", size=40,
           goals=["Protect public sector","Block IMF reforms","Maintain social peace"], constraints=["Co-optation risk","Internal left-right divide","Financial pressure"],
           risk_tolerance="high", time_horizon="long", aliases=["Union Générale Tunisienne du Travail"]),
    Entity(id="BCT", type="institution", label="Central Bank", tier=2, domain=["monetary_policy","foreign_reserves","exchange_rate"],
           power_type="institutional", resources={"popular":2,"institutional":8,"economic":9,"informational":4}, color="#22c55e", size=25,
           goals=["Defend currency","Maintain reserves","Control inflation"], constraints=["Political pressure","Fiscal dominance"],
           risk_tolerance="low", time_horizon="medium", aliases=["Banque Centrale de Tunisie"]),
    Entity(id="ENN", type="institution", label="Ennahda Movement", tier=3, domain=["ideological","electoral_politics","narrative_warfare"],
           power_type="mobilizational", resources={"popular":4,"institutional":3,"economic":5,"informational":5}, color="#a855f7", size=25,
           goals=["Political survival","Anti-authoritarian coalition","International legitimacy"], constraints=["Repression","Internal splits","Electoral decline"],
           risk_tolerance="medium", time_horizon="long", aliases=["Ennahda", "Nahda"]),
    Entity(id="UTICA", type="institution", label="UTICA", tier=3, domain=["economic_policy","social_dialogue","investment"],
           power_type="financial", resources={"popular":3,"institutional":5,"economic":8,"informational":3}, color="#3b82f6", size=20,
           goals=["Business-friendly policy","Tax stability","Avoid unrest"], constraints="Divided membership".split(",")[:1],
           risk_tolerance="low", time_horizon="medium", aliases=["Union Tunisienne de l'Industrie"]),
    Entity(id="ISIE", type="institution", label="ISIE", tier=3, domain=["electoral_politics","constitutional_power"],
           power_type="institutional", resources={"popular":2,"institutional":6,"economic":2,"informational":2}, color="#64748b", size=15,
           goals="Impartial election mgmt".split(","), constraints="Funding gaps".split(","),
           risk_tolerance="low", time_horizon="medium"),
    Entity(id="ARM", type="institution", label="Armed Forces", tier=1, domain=["internal_security","constitutional_power"],
           power_type="institutional", resources={"popular":8,"institutional":8,"economic":4,"informational":3}, color="#10b981", size=35,
           goals=["Professional neutrality","Institutional protection","Anti-terrorism"], constraints=["Economic constraints","Political pressure"],
           risk_tolerance="low", time_horizon="long", aliases=["Army", "Military"]),
    Entity(id="INT", type="institution", label="Ministry of Interior", tier=2, domain=["internal_security","political_repression"],
           power_type="coercive", resources={"popular":2,"institutional":7,"economic":5,"informational":4}, color="#ef4444", size=30,
           goals="Regime protection,Protest control".split(","), constraints="Police morale".split(","),
           risk_tolerance="high", time_horizon="short"),
    Entity(id="COURT", type="institution", label="Judiciary", tier=3, domain=["constitutional_power","human_rights"],
           power_type="institutional", resources={"popular":3,"institutional":5,"economic":2,"informational":3}, color="#f59e0b", size=20,
           goals=["Judicial independence","Rule of law","Anti-corruption"], constraints=["Executive pressure","ISIE tension","Public trust"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="MEDIA", type="institution", label="Media Landscape", tier=3, domain=["narrative_warfare","ideological"],
           power_type="narrative", resources={"popular":5,"institutional":2,"economic":3,"informational":7}, color="#06b6d4", size=20,
           goals=["Fragmented influence","Truth-seeking","Regime criticism"], constraints=["Decree 54","Economic pressure","Polarization"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="LPR", type="actor", label="Labor & Protest", tier=4, domain=["protest_coordination","mobilization","street_politics"],
           power_type="mobilizational", resources={"popular":7,"institutional":1,"economic":2,"informational":5}, color="#f97316", size=18,
           goals="Economic justice,Anti-repression".split(","), constraints=["Fragmentation","Co-optation"],
           risk_tolerance="high", time_horizon="short", aliases=["Protesters", "Street"]),
    Entity(id="INFORMAL", type="actor", label="Informal Economy", tier=4, domain=["border_economy","employment","economic_policy"],
           power_type="structural", resources={"popular":6,"institutional":0,"economic":6,"informational":2}, color="#78716c", size=18,
           goals="Operate freely".split(","), constraints="Crackdowns".split(","),
           risk_tolerance="high", time_horizon="short", aliases=["Parallel market", "Black market"]),
    Entity(id="DONOR", type="institution", label="International Donors", tier=3, domain=["fiscal_policy","structural_reform","investment"],
           power_type="financial", resources={"popular":2,"institutional":6,"economic":8,"informational":4}, color="#6366f1", size=22,
           goals="Reform conditionality,Fiscal discipline".split(","), constraints="Political resistance".split(","),
           risk_tolerance="low", time_horizon="long", aliases=["IMF", "World Bank", "EU donors"]),
    Entity(id="YOUTH", type="actor", label="Youth (Marginalized)", tier=4, domain=["mobilization","employment","street_politics","ideological"],
           power_type="mobilizational", resources={"popular":8,"institutional":1,"economic":1,"informational":6}, color="#a855f7", size=18,
           goals="Employment,Freedom".split(","), constraints="Fragmentation".split(","),
           risk_tolerance="high", time_horizon="short", aliases=["Young Tunisians", "Unemployed graduates"]),
    Entity(id="DIASPORA", type="actor", label="Diaspora", tier=4, domain=["remittance","investment","ideological"],
           power_type="financial", resources={"popular":3,"institutional":2,"economic":7,"informational":3}, color="#ec4899", size=15,
           goals="Economic stability,Family remittances".split(","), constraints=["Limited political leverage","Dual loyalty"],
           risk_tolerance="medium", time_horizon="long", aliases=["Tunisians abroad"]),
    Entity(id="PPL", type="institution", label="Parliament / Political Parties", tier=3, domain=["electoral_politics","legislative","constitutional_power"],
           power_type="institutional", resources={"popular":3,"institutional":4,"economic":3,"informational":4}, color="#94a3b8", size=20,
           goals=["Fragmented opposition","Legislative oversight"], constraints=["Presidential dominance","Polarization","Public contempt"],
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="LTDH", type="actor", label="LTDH (Human Rights League)", tier=4, domain=["human_rights","advocacy","monitoring"],
           power_type="mobilizational", resources={"popular":4,"institutional":3,"economic":2,"informational":6}, color="#06b6d4", size=15,
           goals=["Human rights monitoring","Legal advocacy","International reporting"], constraints=["Decree 54","Funding pressure","Political polarization"],
           risk_tolerance="medium", time_horizon="long", aliases=["Ligue Tunisienne des Droits de l'Homme"]),
    Entity(id="FTDES", type="actor", label="FTDES (Social Rights Forum)", tier=4, domain=["human_rights","social_justice","advocacy"],
           power_type="mobilizational", resources={"popular":5,"institutional":2,"economic":2,"informational":5}, color="#0ea5e9", size=15,
           goals=["Economic & social rights","Migration justice","Anti-torture"], constraints=["Government harassment","Funding constraints"],
           risk_tolerance="high", time_horizon="long", aliases=["Forum Tunisien pour les Droits Économiques et Sociaux"]),
    Entity(id="AWAT", type="actor", label="Al Kawakibi Democracy Center", tier=4, domain=["democracy_promotion","civic_education","advocacy"],
           power_type="mobilizational", resources={"popular":3,"institutional":2,"economic":2,"informational":6}, color="#8b5cf6", size=12,
           goals=["Democratic transition","Youth civic engagement","Policy research"], constraints=["Decree 54","Foreign funding restrictions"],
           risk_tolerance="medium", time_horizon="long", aliases=["Kawakibi Democracy Transition Center"]),
    Entity(id="TNI", type="institution", label="Tunisia News Agencies", tier=4, domain=["media","narrative_warfare","investigative"],
           power_type="narrative", resources={"popular":3,"institutional":1,"economic":2,"informational":5}, color="#64748b", size=12,
           goals=["Independent journalism","Fact-checking","Anti-disinformation"], constraints=["Decree 54","Economic pressure","State media dominance"],
           risk_tolerance="medium", time_horizon="medium", aliases=["Inkyfada","Nawaat","Mena Report"]),
    Entity(id="BAR", type="institution", label="Tunisian Bar Association", tier=4, domain=["legal","human_rights","advocacy"],
           power_type="institutional", resources={"popular":4,"institutional":5,"economic":3,"informational":4}, color="#f59e0b", size=14,
           goals=["Judicial independence","Defense of lawyers","Rule of law"], constraints=["Government pressure","Internal divisions"],
           risk_tolerance="medium", time_horizon="long", aliases=["Ordre National des Avocats de Tunisie"]),
]

NATIONAL_RELATIONS: list[Relation] = [
    Relation(id="dom-1", source_id="PRES", target_id="UGTT", type="competitive", weight=8, domain="social_dialogue",
             description="PRES vs UGTT over wage bill, IMF reform, and public sector layoffs.", trend="rising"),
    Relation(id="dom-2", source_id="PRES", target_id="BCT", type="coercive", weight=7, domain="monetary_policy",
             description="PRES pressure on BCT to monetize debt, threatening independence.", trend="rising"),
    Relation(id="dom-3", source_id="PRES", target_id="INT", type="coercive", weight=9, domain="internal_security",
             description="PRES controls Interior Ministry for protest repression and opposition targeting.", trend="stable"),
    Relation(id="dom-4", source_id="PRES", target_id="ARM", type="cooperative", weight=6, domain="constitutional_power",
             description="PRES maintains careful relationship with military. Army neutrality is a red line.", trend="stable"),
    Relation(id="dom-5", source_id="PRES", target_id="MEDIA", type="coercive", weight=8, domain="narrative_warfare",
             description="Decree 54 used to jail journalists. Media landscape heavily constrained.", trend="rising"),
    Relation(id="dom-6", source_id="PRES", target_id="ENN", type="coercive", weight=7, domain="political_repression",
             description="Ennahda leaders imprisoned, party marginalized, assets seized.", trend="stable"),
    Relation(id="dom-7", source_id="PRES", target_id="COURT", type="coercive", weight=7, domain="constitutional_power",
             description="Presidential control over judiciary via Supreme Judicial Council restructuring.", trend="rising"),
    Relation(id="dom-8", source_id="PRES", target_id="DONOR", type="competitive", weight=5, domain="fiscal_policy",
             description="PRES resists IMF conditions while needing financing. Ongoing stalemate.", trend="stable"),
    Relation(id="dom-9", source_id="UGTT", target_id="PRES", type="competitive", weight=7, domain="labor_organization",
             description="UGTT blocks civil service wage reform and IMF-mandated restructuring.", trend="stable"),
    Relation(id="dom-10", source_id="UGTT", target_id="LPR", type="cooperative", weight=6, domain="protest_coordination",
             description="UGTT channels protest energy. Can mobilize or demobilize the street.", trend="stable"),
    Relation(id="dom-11", source_id="UGTT", target_id="DONOR", type="competitive", weight=5, domain="economic_policy",
             description="UGTT resists donor-mandated austerity, defending public sector wages.", trend="stable"),
    Relation(id="dom-12", source_id="ENN", target_id="UGTT", type="cooperative", weight=4, domain="social_dialogue",
             description="ENN historically allied with UGTT. Relationship strained post-2021.", trend="declining"),
    Relation(id="dom-13", source_id="ENN", target_id="DONOR", type="cooperative", weight=3, domain="diplomatic",
             description="ENN maintains international credibility as democratic opposition.", trend="stable"),
    Relation(id="dom-14", source_id="BCT", target_id="DONOR", type="dependent", weight=8, domain="monetary_policy",
             description="BCT relies on donor FX reserves to defend dinar.", trend="declining"),
    Relation(id="dom-15", source_id="BCT", target_id="INFORMAL", type="extractive", weight=7, domain="exchange_rate",
             description="Parallel market drains FX reserves. BCT cannot control informal currency flows.", trend="rising"),
    Relation(id="dom-16", source_id="YOUTH", target_id="LPR", type="cooperative", weight=7, domain="mobilization",
             description="Marginalized youth are primary protest demographic. High protest elasticity.", trend="stable"),
    Relation(id="dom-17", source_id="DIASPORA", target_id="INFORMAL", type="extractive", weight=4, domain="border_economy",
             description="Diaspora remittances flow through both formal and informal channels.", trend="stable"),
    Relation(id="dom-18", source_id="DONOR", target_id="BCT", type="coercive", weight=6, domain="fiscal_policy",
             description="Donors condition disbursements on reform progress and subsidy phase-out.", trend="stable"),
    Relation(id="dom-19", source_id="PRES", target_id="PPL", type="competitive", weight=5, domain="electoral_politics",
             description="PRES bypasses parliament via decree. Low legislative capacity.", trend="rising"),
    Relation(id="dom-20", source_id="UGTT", target_id="UTICA", type="competitive", weight=3, domain="social_dialogue",
             description="UGTT-UTICA tripartite negotiations for wage-price balance.", trend="stable"),
    Relation(id="dom-21", source_id="INFORMAL", target_id="YOUTH", type="dependent", weight=5, domain="employment",
             description="Informal economy absorbs unemployed youth. Safety valve for social pressure.", trend="stable"),
    Relation(id="dom-22", source_id="PRES", target_id="PRES", type="cooperative", weight=10, domain="constitutional_power", description="Self-loop: regime consolidation.", trend="rising"),
    # Civil society relations
    Relation(id="dom-23", source_id="PRES", target_id="LTDH", type="coercive", weight=6, domain="human_rights",
             description="PRES pressures LTDH via Decree 54 and travel bans on activists.", trend="rising"),
    Relation(id="dom-24", source_id="PRES", target_id="FTDES", type="coercive", weight=5, domain="social_justice",
             description="FTDES offices raided, staff detained for reporting on migration and social conditions.", trend="rising"),
    Relation(id="dom-25", source_id="PRES", target_id="AWAT", type="coercive", weight=4, domain="democracy_promotion",
             description="Kawakibi Center faces foreign funding investigation and operational restrictions.", trend="rising"),
    Relation(id="dom-26", source_id="PRES", target_id="BAR", type="coercive", weight=7, domain="legal",
             description="PRES targets bar association leadership, arrests prominent lawyers, challenges professional autonomy.", trend="rising"),
    Relation(id="dom-27", source_id="LTDH", target_id="COURT", type="cooperative", weight=5, domain="human_rights",
             description="LTDH collaborates with judiciary on human rights cases and legal advocacy.", trend="stable"),
    Relation(id="dom-28", source_id="FTDES", target_id="LPR", type="cooperative", weight=4, domain="social_justice",
             description="FTDES supports protest movements on economic rights and social justice issues.", trend="stable"),
    Relation(id="dom-29", source_id="AWAT", target_id="YOUTH", type="cooperative", weight=4, domain="civic_education",
             description="Kawakibi Center runs youth civic education and democracy workshops.", trend="stable"),
    Relation(id="dom-30", source_id="BAR", target_id="COURT", type="cooperative", weight=6, domain="legal",
             description="Bar Association defends judicial independence and coordinates with judiciary on rule of law.", trend="stable"),
    Relation(id="dom-31", source_id="LTDH", target_id="MEDIA", type="cooperative", weight=4, domain="advocacy",
             description="LTDH partners with media for human rights reporting and awareness campaigns.", trend="stable"),
    Relation(id="dom-32", source_id="UGTT", target_id="LTDH", type="cooperative", weight=3, domain="social_dialogue",
             description="UGTT and LTDH coordinate on social justice issues and labor rights advocacy.", trend="stable"),
]

# ── Infrastructure (power plants, ports, water, transport) ────────

INFRASTRUCTURE_ENTITIES: list[Entity] = [
    # ── Energy ──────────────────────────────────────────────────────
    Entity(id="STEG", type="utility", label="STEG (National Grid)", tier=2, domain=["energy","electricity","subsidies"],
           power_type="structural", resources={"economic":8,"institutional":7,"technical":9,"informational":3}, color="#f97316", size=35,
           goals=["Grid stability","Reduce STEG debt","Integrate renewables"], constraints=["Gas import dependency","Aging infrastructure","Subsidy burden"],
           risk_tolerance="medium", time_horizon="long", aliases=["Société Tunisienne de l'Électricité et du Gaz"]),
    Entity(id="RADES_PP", type="infrastructure", label="Radès Power Plant", tier=2, domain=["energy","electricity"],
           power_type="structural", resources={"economic":5,"technical":7}, color="#fb923c", size=22,
           goals=["Baseload generation","Peak demand coverage"], constraints=["Aging gas turbines","Fuel supply dependency"],
           risk_tolerance="medium", time_horizon="medium", aliases=["Centrale de Radès"]),
    Entity(id="SOUSSE_PP", type="infrastructure", label="Sousse Power Plant", tier=3, domain=["energy"],
           power_type="structural", resources={"economic":4,"technical":6}, color="#fdba74", size=18,
           goals=["Regional electricity supply"], constraints=["Gas supply","Maintenance backlog"],
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="SFAX_PP", type="infrastructure", label="Sfax Power Plant", tier=3, domain=["energy"],
           power_type="structural", resources={"economic":3,"technical":5}, color="#fed7aa", size=16,
           goals=["Southern grid stability"], constraints=["Fuel costs","Efficiency losses"],
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="GABES_PP", type="infrastructure", label="Gabès Power Plant", tier=4, domain=["energy","industry"],
           power_type="structural", resources={"economic":2,"technical":4}, color="#ffedd5", size=14,
           goals=["Industrial cogeneration","Chemical hub supply"], constraints=["Environmental compliance","Aging equipment"],
           risk_tolerance="medium", time_horizon="short"),
    Entity(id="HAOUARIA_WIND", type="infrastructure", label="El Haouaria Wind Farm", tier=4, domain=["energy","renewables"],
           power_type="structural", resources={"economic":2,"technical":5}, color="#66bb6a", size=12,
           goals=["Renewable capacity","Wind energy diversification"], constraints=["Intermittency","Grid integration"],
           risk_tolerance="low", time_horizon="long", aliases=["Parc Éolien d'El Haouaria"]),
    Entity(id="CPG", type="institution", label="CPG (Phosphate Company)", tier=3, domain=["industry","phosphate","mining","trade"],
           power_type="structural", resources={"economic":7,"industrial":8,"logistics":6}, color="#f59e0b", size=22,
           goals=["Phosphate production & export","Gafsa basin employment","State revenue"], constraints=["Depleting reserves","Environmental damage","Global price volatility"],
           risk_tolerance="medium", time_horizon="long", aliases=["Compagnie des Phosphates de Gafsa"]),
    Entity(id="TOZEUR_SOLAR", type="infrastructure", label="Tozeur Solar Farm", tier=4, domain=["energy","renewables"],
           power_type="structural", resources={"economic":1,"technical":3}, color="#81c784", size=10,
           goals=["Desert solar potential","Southern electrification"], constraints=["Small capacity","Sand/solar panel maintenance"],
           risk_tolerance="low", time_horizon="long"),
    # ── Ports ────────────────────────────────────────────────────────
    Entity(id="RADES_PORT", type="infrastructure", label="Radès Port", tier=2, domain=["trade","logistics","import_export"],
           power_type="structural", resources={"economic":9,"logistics":9}, color="#3b82f6", size=28,
           goals=["Container throughput","Import clearance efficiency"], constraints=["Congestion","Draft depth limits","Customs delays"],
           risk_tolerance="medium", time_horizon="medium", aliases=["Port de Radès"]),
    Entity(id="SFAX_PORT", type="infrastructure", label="Sfax Port", tier=3, domain=["trade","fishing","logistics"],
           power_type="structural", resources={"economic":5,"logistics":6}, color="#60a5fa", size=20,
           goals=["Commercial & fishing operations","Regional export hub"], constraints=["Siltation","Limited container capacity"],
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="GABES_PORT", type="infrastructure", label="Gabès Port", tier=3, domain=["industry","chemicals","trade"],
           power_type="structural", resources={"economic":6,"logistics":5}, color="#93c5fd", size=18,
           goals=["Phosphate & chemical exports","Industrial zone supply"], constraints=["Environmental damage","Industrial accident risk"],
           risk_tolerance="high", time_horizon="medium", aliases=["Port de Gabès"]),
    Entity(id="BIZERTE_PORT", type="infrastructure", label="Bizerte Port", tier=3, domain=["trade","military","logistics"],
           power_type="structural", resources={"economic":4,"logistics":6,"military":5}, color="#2563eb", size=20,
           goals=["Commercial & naval operations","Hydrocarbon storage"], constraints=["Competition with Radès","Infrastructure age"],
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="SKHIRA_PORT", type="infrastructure", label="Skhira Port", tier=3, domain=["industry","phosphate","trade"],
           power_type="structural", resources={"economic":5,"logistics":4}, color="#bfdbfe", size=16,
           goals=["Phosphate export hub","CPG logistics"], constraints=["Single-commodity dependency","Environmental risk"],
           risk_tolerance="medium", time_horizon="long", aliases=["Port de Skhira", "CPG Skhira"]),
    Entity(id="ZARZIS_PORT", type="infrastructure", label="Zarzis Port", tier=4, domain=["petroleum","trade","fishing"],
           power_type="structural", resources={"economic":3,"logistics":3}, color="#dbeafe", size=12,
           goals=["Petroleum product handling","Fishing fleet support"], constraints=["Limited capacity","Remote location"],
           risk_tolerance="medium", time_horizon="medium"),
    # ── Water ────────────────────────────────────────────────────────
    Entity(id="SONEDE", type="utility", label="SONEDE (Water Utility)", tier=2, domain=["water","infrastructure","environment"],
           power_type="structural", resources={"economic":6,"institutional":7,"technical":8}, color="#06b6d4", size=32,
           goals=["Water distribution","Leak reduction","Desalination expansion"], constraints=["Dam depletion","Network losses (35%+)","Climate stress"],
           risk_tolerance="medium", time_horizon="long", aliases=["Société Nationale d'Exploitation et de Distribution des Eaux"]),
    Entity(id="DAM_SALEM", type="infrastructure", label="Sidi Salem Dam", tier=2, domain=["water","agriculture","environment"],
           power_type="structural", resources={"economic":7,"water_capacity":580}, color="#22d3ee", size=26,
           goals=["Water storage (580M m³)","Irrigation supply","Flood control"], constraints=["Siltation","Climate change","Evaporation losses"],
           risk_tolerance="medium", time_horizon="long", aliases=["Barrage Sidi Salem"]),
    Entity(id="DAM_BARRAK", type="infrastructure", label="Sidi Barrak Dam", tier=3, domain=["water","agriculture"],
           power_type="structural", resources={"economic":5,"water_capacity":270}, color="#67e8f9", size=22,
           goals=["Water storage (270M m³)","North-west water security"], constraints=["Siltation","Reduced rainfall"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="DAM_MCHERGA", type="infrastructure", label="Bir M'cherga Dam", tier=4, domain=["water"],
           power_type="structural", resources={"economic":3,"water_capacity":130}, color="#a5f3fc", size=16,
           goals=["Water storage (130M m³)","Cap Bon supply"], constraints="Siltation,Evaporation".split(","),
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="DAM_ELKEBIR", type="infrastructure", label="Oued El Kebir Dam", tier=4, domain=["water"],
           power_type="structural", resources={"economic":3,"water_capacity":100}, color="#cffafe", size=14,
           goals=["Water storage (100M m³)","North-west supply"], constraints="Siltation,Construction delays".split(","),
           risk_tolerance="medium", time_horizon="medium"),
    Entity(id="PIPELINE_NS", type="infrastructure", label="North-South Water Pipeline", tier=2, domain=["water","infrastructure"],
           power_type="structural", resources={"economic":8,"technical":7}, color="#0891b2", size=24,
           goals=["Transfer north water to south","Drought relief","Irrigation"], constraints=["High operating cost","Pumping power needs","Leakage"],
           risk_tolerance="high", time_horizon="long", aliases=["Adduction Nord-Sud", "Water transfer pipeline"]),
    Entity(id="DESAL_SFAX", type="infrastructure", label="Sfax Desalination Plant", tier=4, domain=["water","infrastructure"],
           power_type="structural", resources={"economic":4,"technical":5}, color="#22d3ee", size=14,
           goals=["Sfax freshwater supply","Reduce aquifer depletion"], constraints=["Energy cost","Brine discharge","Phased construction"],
           risk_tolerance="medium", time_horizon="long"),
    Entity(id="DESAL_DJERBA", type="infrastructure", label="Djerba Desalination Plant", tier=4, domain=["water"],
           power_type="structural", resources={"economic":2,"technical":3}, color="#67e8f9", size=10,
           goals=["Island water security","Tourism supply"], constraints="Energy cost,Salinity".split(","),
           risk_tolerance="medium", time_horizon="medium"),
    # ── Transport ────────────────────────────────────────────────────
    Entity(id="A1_HWY", type="infrastructure", label="A1 Highway (Tunis-Sfax)", tier=2, domain=["transport","logistics","trade"],
           power_type="structural", resources={"economic":9,"logistics":9}, color="#a855f7", size=26,
           goals=["North-south freight corridor","Regional connectivity"], constraints=["Toll revenue","Maintenance backlog","Accident rates"],
           risk_tolerance="low", time_horizon="long", aliases=["Autoroute A1"]),
    Entity(id="A3_HWY", type="infrastructure", label="A3 Highway (Tunis-West)", tier=3, domain=["transport","logistics"],
           power_type="structural", resources={"economic":5,"logistics":6}, color="#c084fc", size=20,
           goals=["Western corridor access","Algerian border connectivity"], constraints="Construction phasing,Toll compliance".split(","),
           risk_tolerance="low", time_horizon="long", aliases=["Autoroute A3"]),
    Entity(id="A4_HWY", type="infrastructure", label="A4 Highway (Tunis-Bizerte)", tier=3, domain=["transport","logistics"],
           power_type="structural", resources={"economic":4,"logistics":5}, color="#d8b4fe", size=18,
           goals=["Northern corridor","Port of Bizerte access"], constraints="Toll adoption,Environmental reviews".split(","),
           risk_tolerance="low", time_horizon="long", aliases=["Autoroute A4"]),
    Entity(id="SNCFT", type="utility", label="SNCFT (National Railway)", tier=2, domain=["transport","logistics","industry"],
           power_type="structural", resources={"economic":5,"institutional":6,"technical":5}, color="#ec4899", size=24,
           goals=["Passenger & freight rail","Phosphate transport","Urban commuter service"], constraints=["Aging rolling stock","Underinvestment","Low speed"],
           risk_tolerance="medium", time_horizon="long", aliases=["Société Nationale des Chemins de Fer Tunisiens"]),
    Entity(id="TUNIS_AIRPORT", type="infrastructure", label="Tunis-Carthage Airport", tier=2, domain=["transport","tourism","trade"],
           power_type="structural", resources={"economic":7,"logistics":7}, color="#f472b6", size=24,
           goals=["International air hub","Tourism gateway","Cargo operations"], constraints=["Runway capacity","Aging terminals","Airspace constraints"],
           risk_tolerance="low", time_horizon="long", aliases=["Aéroport Tunis-Carthage"]),
    Entity(id="ENFIDHA_AIRPORT", type="infrastructure", label="Enfidha-Hammamet Airport", tier=3, domain=["transport","tourism"],
           power_type="structural", resources={"economic":5,"logistics":5}, color="#f9a8d4", size=18,
           goals=["Tourist charter hub","Hammamet & Port El Kantaoui access"], constraints=["Seasonal demand","Underutilized capacity"],
           risk_tolerance="low", time_horizon="long", aliases=["Aéroport Enfidha-Hammamet"]),
    Entity(id="DJERBA_AIRPORT", type="infrastructure", label="Djerba-Zarzis Airport", tier=3, domain=["transport","tourism"],
           power_type="structural", resources={"economic":4,"logistics":4}, color="#fbcfe8", size=16,
           goals=["Djerba tourism access","Southern connectivity"], constraints="Seasonal,Tunis-Carthage competition".split(","),
           risk_tolerance="low", time_horizon="long", aliases=["Aéroport Djerba-Zarzis"]),
    Entity(id="RADES_RAIL", type="infrastructure", label="Radès Railway Freight Hub", tier=3, domain=["transport","logistics","trade"],
           power_type="structural", resources={"economic":5,"logistics":6}, color="#fb7185", size=16,
           goals=["Port-rail intermodal transfer","Freight consolidation"], constraints=["Gauge incompatibility","Underinvestment"],
           risk_tolerance="medium", time_horizon="medium"),
]

INFRASTRUCTURE_RELATIONS: list[Relation] = [
    # ── Power grid ────────────────────────────────────────────────
    Relation(id="infra-1", source_id="STEG", target_id="RADES_PP", type="cooperative", weight=9, domain="energy",
             description="Radès is STEG's largest plant, supplying ~20% of national capacity.", trend="stable"),
    Relation(id="infra-2", source_id="STEG", target_id="SOUSSE_PP", type="cooperative", weight=7, domain="energy",
             description="Sousse plant supplies Sahel region grid.", trend="stable"),
    Relation(id="infra-3", source_id="STEG", target_id="SFAX_PP", type="cooperative", weight=6, domain="energy",
             description="Sfax plant serves southern industrial demand.", trend="declining"),
    Relation(id="infra-4", source_id="STEG", target_id="GABES_PP", type="cooperative", weight=4, domain="energy",
             description="Gabès cogeneration supplies chemical complex.", trend="stable"),
    Relation(id="infra-5", source_id="STEG", target_id="HAOUARIA_WIND", type="cooperative", weight=3, domain="renewables",
             description="Wind farm contributes to renewable target (4.1% of mix).", trend="rising"),
    Relation(id="infra-6", source_id="STEG", target_id="TOZEUR_SOLAR", type="cooperative", weight=2, domain="renewables",
             description="Solar pilot — small but strategic for desert potential.", trend="rising"),
    Relation(id="infra-7", source_id="TUN", target_id="STEG", type="dependent", weight=8, domain="energy",
             description="STEG debt of 4.2B TND is a sovereign fiscal risk. Gas imports strain FX reserves.", trend="declining"),
    Relation(id="infra-8", source_id="DZA", target_id="STEG", type="dependent", weight=7, domain="energy",
             description="Algeria supplies 60%+ of STEG's natural gas via ENI pipeline.", trend="stable"),
    # ── Ports ─────────────────────────────────────────────────────
    Relation(id="infra-9", source_id="TUN", target_id="RADES_PORT", type="dependent", weight=9, domain="trade",
             description="Radès handles ~60% of Tunisia's container traffic. Critical import/export node.", trend="stable"),
    Relation(id="infra-10", source_id="RADES_PORT", target_id="TUN", type="extractive", weight=7, domain="logistics",
             description="Port congestion creates import delays and cost inflation.", trend="declining"),
    Relation(id="infra-11", source_id="RADES_PORT", target_id="RADES_RAIL", type="cooperative", weight=5, domain="logistics",
             description="Intermodal freight transfer between port and rail.", trend="stable"),
    Relation(id="infra-12", source_id="SFAX_PORT", target_id="SFAX_PP", type="cooperative", weight=4, domain="industry",
             description="Sfax Port supplies fuel for Sfax power plant.", trend="stable"),
    Relation(id="infra-13", source_id="GABES_PORT", target_id="GABES_PP", type="cooperative", weight=5, domain="industry",
             description="Gabès Port handles chemical inputs for the industrial complex.", trend="stable"),
    Relation(id="infra-14", source_id="SKHIRA_PORT", target_id="CPG", type="dependent", weight=8, domain="phosphate",
             description="Skhira is CPG's primary phosphate export terminal. ~4M tons/year.", trend="stable"),
    Relation(id="infra-15", source_id="SKHIRA_PORT", target_id="TUN", type="extractive", weight=6, domain="trade",
             description="Phosphate exports via Skhira are a key hard-currency earner.", trend="stable"),
    Relation(id="infra-16", source_id="BIZERTE_PORT", target_id="TUN", type="cooperative", weight=5, domain="trade",
             description="Bizerte handles hydrocarbons, bulk cargo, and some military traffic.", trend="stable"),
    Relation(id="infra-17", source_id="BIZERTE_PORT", target_id="ARM", type="cooperative", weight=4, domain="military",
             description="Bizerte has naval facilities used by Tunisian Navy.", trend="stable"),
    # ── Water ──────────────────────────────────────────────────────
    Relation(id="infra-18", source_id="SONEDE", target_id="DAM_SALEM", type="dependent", weight=9, domain="water",
             description="Sidi Salem is SONEDE's primary reservoir (580M m³) for potable water.", trend="stable"),
    Relation(id="infra-19", source_id="SONEDE", target_id="DAM_BARRAK", type="dependent", weight=7, domain="water",
             description="Sidi Barrak (270M m³) supplements northern supply.", trend="stable"),
    Relation(id="infra-20", source_id="SONEDE", target_id="DAM_MCHERGA", type="cooperative", weight=5, domain="water",
             description="Bir M'cherga (130M m³) serves Cap Bon peninsula.", trend="stable"),
    Relation(id="infra-21", source_id="SONEDE", target_id="PIPELINE_NS", type="dependent", weight=8, domain="water",
             description="North-South pipeline transfers water from north dams to dry south.", trend="stable"),
    Relation(id="infra-22", source_id="SONEDE", target_id="DESAL_SFAX", type="cooperative", weight=5, domain="water",
             description="Sfax desalination reduces aquifer overdraft.", trend="rising"),
    Relation(id="infra-23", source_id="SONEDE", target_id="DESAL_DJERBA", type="cooperative", weight=3, domain="water",
             description="Djerba desalination provides island water security.", trend="stable"),
    Relation(id="infra-24", source_id="TUN", target_id="SONEDE", type="dependent", weight=8, domain="water",
             description="SONEDE's network losses (35%+) and dam depletion threaten national water security.", trend="declining"),
    Relation(id="infra-25", source_id="DAM_SALEM", target_id="PIPELINE_NS", type="cooperative", weight=7, domain="water",
             description="Sidi Salem feeds the north-south pipeline system.", trend="stable"),
    # ── Transport ─────────────────────────────────────────────────
    Relation(id="infra-26", source_id="A1_HWY", target_id="RADES_PORT", type="cooperative", weight=8, domain="logistics",
             description="A1 connects Radès Port to Sfax and the south. Primary freight route.", trend="stable"),
    Relation(id="infra-27", source_id="A1_HWY", target_id="TUNIS_AIRPORT", type="cooperative", weight=5, domain="transport",
             description="A1 provides airport access from southern regions.", trend="stable"),
    Relation(id="infra-28", source_id="A4_HWY", target_id="BIZERTE_PORT", type="cooperative", weight=6, domain="transport",
             description="A4 connects Bizerte Port to Tunis and the A1 corridor.", trend="stable"),
    Relation(id="infra-29", source_id="A3_HWY", target_id="TUN", type="cooperative", weight=4, domain="transport",
             description="A3 extends westward toward Oued Zarga and the Algerian border.", trend="stable"),
    Relation(id="infra-30", source_id="SNCFT", target_id="RADES_RAIL", type="cooperative", weight=6, domain="rail",
             description="Radès is SNCFT's primary freight rail hub for port intermodal.", trend="stable"),
    Relation(id="infra-31", source_id="SNCFT", target_id="CPG", type="dependent", weight=7, domain="industry",
             description="SNCFT transports CPG phosphate from Gafsa mines to Skhira Port.", trend="stable"),
    Relation(id="infra-32", source_id="SNCFT", target_id="SKHIRA_PORT", type="cooperative", weight=6, domain="logistics",
             description="Phosphate rail line feeds directly into Skhira Port export terminal.", trend="stable"),
    Relation(id="infra-33", source_id="TUNIS_AIRPORT", target_id="TUN", type="extractive", weight=6, domain="tourism",
             description="Tunis-Carthage is primary international gateway for tourism and business.", trend="stable"),
    Relation(id="infra-34", source_id="ENFIDHA_AIRPORT", target_id="TUN", type="extractive", weight=4, domain="tourism",
             description="Enfidha serves Sahel tourist zone (Hammamet, Sousse, Monastir).", trend="stable"),
    Relation(id="infra-35", source_id="DJERBA_AIRPORT", target_id="TUN", type="extractive", weight=4, domain="tourism",
             description="Djerba airport serves island tourism economy.", trend="stable"),
    Relation(id="infra-36", source_id="A1_HWY", target_id="SNCFT", type="competitive", weight=3, domain="transport",
             description="Highway and railway compete for freight and passenger traffic on the Tunis-Sfax corridor.", trend="stable"),
    Relation(id="infra-37", source_id="SONEDE", target_id="STEG", type="dependent", weight=6, domain="energy",
             description="SONEDE is STEG's largest single electricity consumer (pumping stations + desalination).", trend="rising"),
    Relation(id="infra-38", source_id="RADES_PORT", target_id="TUNIS_AIRPORT", type="cooperative", weight=2, domain="logistics",
             description="Both serve Greater Tunis as key trade and travel gateways.", trend="stable"),
]
