"""
Seed 11 actor cognition profiles for TunisiaIntel Phase 4.

Each profile encodes objectives, fears, decision style, input sensitivity,
output probability matrix, state update rules, authority weights,
coalition affinities, veto conditions, and historical patterns.

Profiles PRES, UGTT, ARM, INT, BCT, LPR, EU are fully specified in the spec.
Profiles DZA, UTICA, DONOR, PPL are built from condensed specs following
the same schema. All start as status: draft.
"""

from __future__ import annotations

from typing import Any, Dict, List

PROFILES: List[Dict[str, Any]] = [
    # ── PROFILE-01: Presidency (PRES) ────────────────────────────────
    {
        "entity_id": "PRES",
        "actor_name": "Presidency / Executive Authority",
        "actor_class": "national",
        "doctrine": "regime_survival_through_concentration",
        "decision_style": "centralized",
        "risk_tolerance": 0.72,
        "time_horizon": "short",
        "objectives": [
            {"goal": "maintain executive control", "weight": 0.98, "time_horizon": "short"},
            {"goal": "prevent elite fracture", "weight": 0.90, "time_horizon": "short"},
            {"goal": "secure international legitimacy", "weight": 0.75, "time_horizon": "medium"},
            {"goal": "manage IMF relationship", "weight": 0.70, "time_horizon": "medium"},
            {"goal": "neutralize organized opposition", "weight": 0.85, "time_horizon": "short"},
        ],
        "fears": [
            {"fear": "military_neutrality", "threshold": 0.60, "reaction": "immediate_concession_or_flight"},
            {"fear": "mass_unrest_sustained", "threshold": 0.75, "reaction": "repression_then_negotiation"},
            {"fear": "elite_defection_cascade", "threshold": 0.50, "reaction": "preemptive_reshuffle"},
            {"fear": "foreign_isolation", "threshold": 0.65, "reaction": "diplomatic_speech"},
            {"fear": "economic_collapse", "threshold": 0.80, "reaction": "delay_blame_shift"},
        ],
        "preferred_tools": [
            "legal_decrees", "media_narrative_reset", "security_pressure",
            "symbolic_speeches", "reshuffles", "internet_throttling",
            "targeted_arrests", "foreign_diplomacy",
        ],
        "input_sensitivity": {
            "unrest": 0.95,
            "elite_cohesion": 0.92,
            "military_posture": 0.98,
            "imf_pressure": 0.80,
            "foreign_pressure": 0.75,
            "narrative_convergence": 0.70,
            "ugtt_strike_index": 0.65,
            "p_revolution": 0.99,
        },
        "output_probability_matrix": {
            "repression": 0.65,
            "concessions": 0.20,
            "distraction_narrative": 0.55,
            "reshuffle": 0.35,
            "speech": 0.60,
            "arrest_opposition": 0.40,
            "internet_throttling": 0.30,
            "imf_delay": 0.75,
            "foreign_outreach": 0.45,
        },
        "state_update_rules": [
            {"if_signal": "military_posture", "operator": "<", "threshold": 0.40,
             "then_action": "concessions", "delta": 0.40,
             "and_action": "repression", "and_delta": -0.35},
            {"if_signal": "unrest", "operator": ">", "threshold": 0.75,
             "then_action": "repression", "delta": 0.20,
             "and_action": "speech", "and_delta": 0.15},
            {"if_signal": "elite_cohesion", "operator": "<", "threshold": 0.40,
             "then_action": "reshuffle", "delta": 0.30},
            {"if_signal": "p_revolution", "operator": ">", "threshold": 0.60,
             "then_action": "imf_delay", "delta": 0.20,
             "and_action": "distraction_narrative", "and_delta": 0.25},
        ],
        "authority_weights": {
            "economic_crisis": 0.70,
            "security_crisis": 0.90,
            "labor_crisis": 0.60,
            "legitimacy_crisis": 0.85,
            "foreign_pressure": 0.80,
        },
        "coalition_affinities": [
            {"entity_id": "INT", "affinity": 0.85, "condition": "any"},
            {"entity_id": "ARM", "affinity": 0.60, "condition": "any"},
            {"entity_id": "BCT", "affinity": 0.50, "condition": "economic_crisis"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2021_self_coup", "behavior": "concentrated_power", "rri_estimate": 1.8,
             "trigger": "parliamentary_deadlock + public_frustration"},
            {"event": "2023_imf_negotiation", "behavior": "delayed_reforms", "pattern": "promise_then_defer"},
            {"event": "2024_arrests", "behavior": "targeted_opposition_arrest", "trigger": "narrative_threat"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2011, "event": "Ben Ali exit sequence", "match": 0.0},
            {"year": 2021, "event": "Self-coup power consolidation", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-02: UGTT ─────────────────────────────────────────────
    {
        "entity_id": "UGTT",
        "actor_name": "UGTT — Union Générale Tunisienne du Travail",
        "actor_class": "civil",
        "doctrine": "class_interest_with_national_legitimacy_role",
        "decision_style": "consensus",
        "risk_tolerance": 0.45,
        "time_horizon": "medium",
        "objectives": [
            {"goal": "protect wage levels against inflation", "weight": 0.95, "time_horizon": "short"},
            {"goal": "block subsidy removal", "weight": 0.90, "time_horizon": "short"},
            {"goal": "maintain institutional legitimacy", "weight": 0.85, "time_horizon": "medium"},
            {"goal": "negotiate from strength not rupture", "weight": 0.80, "time_horizon": "medium"},
            {"goal": "prevent regime from bypassing labor law", "weight": 0.75, "time_horizon": "medium"},
        ],
        "fears": [
            {"fear": "loss_of_negotiating_relevance", "threshold": 0.50, "reaction": "escalate_to_general_strike"},
            {"fear": "wage_erosion_above_15pct_real", "threshold": 0.60, "reaction": "sector_strikes_then_national"},
            {"fear": "legal_dissolution_threat", "threshold": 0.70, "reaction": "international_solidarity_activation"},
            {"fear": "internal_factional_split", "threshold": 0.55, "reaction": "leadership_consolidation"},
        ],
        "preferred_tools": [
            "sector_strikes", "general_strike_threat", "negotiation",
            "public_statements", "international_labor_solidarity",
            "civil_society_coalition", "press_conferences",
        ],
        "input_sensitivity": {
            "inflation_rate": 0.95,
            "real_wage_index": 0.90,
            "repression_index": 0.75,
            "subsidy_removal_signal": 0.98,
            "public_anger": 0.70,
            "imf_conditionality": 0.85,
            "unemployment_rate": 0.80,
        },
        "output_probability_matrix": {
            "negotiation": 0.70,
            "sector_strike": 0.45,
            "general_strike": 0.20,
            "public_statement": 0.80,
            "neutrality": 0.35,
            "coalition_with_opposition": 0.30,
            "international_appeal": 0.40,
        },
        "state_update_rules": [
            {"if_signal": "subsidy_removal_signal", "operator": ">", "threshold": 0.70,
             "then_action": "general_strike", "delta": 0.55,
             "and_action": "negotiation", "and_delta": -0.20},
            {"if_signal": "inflation_rate", "operator": ">", "threshold": 0.12,
             "then_action": "sector_strike", "delta": 0.30},
            {"if_signal": "repression_index", "operator": ">", "threshold": 0.70,
             "then_action": "international_appeal", "delta": 0.35,
             "and_action": "general_strike", "and_delta": 0.20},
        ],
        "authority_weights": {
            "economic_crisis": 0.85,
            "security_crisis": 0.25,
            "labor_crisis": 0.98,
            "legitimacy_crisis": 0.60,
            "foreign_pressure": 0.30,
        },
        "coalition_affinities": [
            {"entity_id": "LPR", "affinity": 0.70, "condition": "legitimacy_crisis"},
            {"entity_id": "PPL", "affinity": 0.80, "condition": "any"},
            {"entity_id": "FTDES", "affinity": 0.65, "condition": "labor_crisis"},
        ],
        "veto_conditions": [
            {"condition": "ugtt_strike_index > 0.75", "blocks": "subsidy_removal",
             "historical_basis": "Every subsidy removal attempt 2011-2024 required UGTT consent"},
        ],
        "historical_patterns": [
            {"event": "2013_national_dialogue", "behavior": "mediated_crisis", "role": "kingmaker"},
            {"event": "2012_general_strike", "behavior": "escalated_then_negotiated"},
            {"event": "2022_wage_negotiations", "behavior": "accepted_partial_deal_under_fiscal_pressure"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2013, "event": "National dialogue mediation", "match": 0.0},
            {"year": 2012, "event": "General strike", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-03: Military (ARM) ────────────────────────────────────
    {
        "entity_id": "ARM",
        "actor_name": "Tunisian Armed Forces",
        "actor_class": "security",
        "doctrine": "institutional_preservation_through_neutrality",
        "decision_style": "centralized",
        "risk_tolerance": 0.25,
        "time_horizon": "long",
        "objectives": [
            {"goal": "preserve institutional integrity", "weight": 0.98, "time_horizon": "long"},
            {"goal": "avoid direct political entanglement", "weight": 0.90, "time_horizon": "long"},
            {"goal": "maintain foreign military partnerships", "weight": 0.80, "time_horizon": "medium"},
            {"goal": "protect border security", "weight": 0.85, "time_horizon": "short"},
            {"goal": "prevent civil war scenario", "weight": 0.95, "time_horizon": "short"},
        ],
        "fears": [
            {"fear": "ordered_to_fire_on_civilians", "threshold": 0.50, "reaction": "neutrality_declaration"},
            {"fear": "institutional_fragmentation", "threshold": 0.40, "reaction": "internal_consolidation"},
            {"fear": "foreign_military_aid_suspension", "threshold": 0.60, "reaction": "diplomatic_signal_to_west"},
            {"fear": "regime_collapse_creating_vacuum", "threshold": 0.65, "reaction": "transitional_stabilization_role"},
        ],
        "preferred_tools": [
            "neutrality_declaration", "silent_pressure_on_presidency",
            "border_deployment", "transitional_stabilization",
            "foreign_partnership_signaling",
        ],
        "input_sensitivity": {
            "p_revolution": 0.95,
            "elite_cohesion": 0.85,
            "civilian_casualty_risk": 0.99,
            "foreign_pressure": 0.70,
            "institutional_legitimacy": 0.90,
            "unrest": 0.80,
        },
        "output_probability_matrix": {
            "neutrality": 0.75,
            "regime_support": 0.50,
            "silent_pressure": 0.40,
            "transitional_role": 0.15,
            "intervention": 0.05,
            "border_deployment": 0.60,
        },
        "state_update_rules": [
            {"if_signal": "p_revolution", "operator": ">", "threshold": 0.55,
             "then_action": "neutrality", "delta": 0.30,
             "and_action": "regime_support", "and_delta": -0.35},
            {"if_signal": "civilian_casualty_risk", "operator": ">", "threshold": 0.60,
             "then_action": "neutrality", "delta": 0.45},
            {"if_signal": "elite_cohesion", "operator": "<", "threshold": 0.30,
             "then_action": "transitional_role", "delta": 0.40},
        ],
        "authority_weights": {
            "economic_crisis": 0.20,
            "security_crisis": 0.90,
            "labor_crisis": 0.15,
            "legitimacy_crisis": 0.95,
            "foreign_pressure": 0.60,
        },
        "coalition_affinities": [
            {"entity_id": "INT", "affinity": 0.55, "condition": "security_crisis"},
            {"entity_id": "PRES", "affinity": 0.60, "condition": "any"},
        ],
        "veto_conditions": [
            {"condition": "civilian_casualty_order = true",
             "blocks": "any_action",
             "historical_basis": "2011 — military refused Ben Ali order to fire on protesters"},
        ],
        "historical_patterns": [
            {"event": "2011_revolution", "behavior": "refused_to_fire_on_protesters",
             "effect": "regime_collapse_accelerated", "rri_at_event": 2.85},
            {"event": "2021_self_coup", "behavior": "supported_presidential_power_grab",
             "condition": "framed_as_constitutional_not_military"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2011, "event": "Military refused to fire on protesters", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-04: Interior Ministry (INT) ───────────────────────────
    {
        "entity_id": "INT",
        "actor_name": "Ministry of Interior / Security Apparatus",
        "actor_class": "security",
        "doctrine": "order_maintenance_through_coercion",
        "decision_style": "centralized",
        "risk_tolerance": 0.60,
        "time_horizon": "short",
        "objectives": [
            {"goal": "suppress protest before it spreads", "weight": 0.95, "time_horizon": "short"},
            {"goal": "protect strategic infrastructure", "weight": 0.85, "time_horizon": "short"},
            {"goal": "monitor opposition networks", "weight": 0.90, "time_horizon": "medium"},
            {"goal": "manage border and migration flows", "weight": 0.75, "time_horizon": "medium"},
        ],
        "fears": [
            {"fear": "protest_exceeding_containment_capacity", "threshold": 0.70,
             "reaction": "request_military_support"},
            {"fear": "international_scrutiny_of_methods", "threshold": 0.60,
             "reaction": "reduce_visible_violence"},
            {"fear": "budget_cut_reducing_capacity", "threshold": 0.50,
             "reaction": "loyalty_signal_to_presidency"},
        ],
        "preferred_tools": [
            "mass_arrests", "tear_gas_water_cannon", "surveillance_expansion",
            "targeted_opposition_arrests", "border_control",
            "internet_monitoring", "informant_networks",
        ],
        "input_sensitivity": {
            "protest_intensity": 0.98,
            "regional_spread": 0.90,
            "foreign_scrutiny": 0.65,
            "budget_constraints": 0.55,
            "presidential_directive": 0.99,
        },
        "output_probability_matrix": {
            "crackdown": 0.75,
            "targeted_arrests": 0.65,
            "surveillance_expansion": 0.80,
            "border_tightening": 0.60,
            "reduced_visibility": 0.30,
        },
        "state_update_rules": [
            {"if_signal": "protest_intensity", "operator": ">", "threshold": 0.80,
             "then_action": "crackdown", "delta": 0.20},
            {"if_signal": "foreign_scrutiny", "operator": ">", "threshold": 0.75,
             "then_action": "reduced_visibility", "delta": 0.35,
             "and_action": "crackdown", "and_delta": -0.25},
        ],
        "authority_weights": {
            "economic_crisis": 0.20,
            "security_crisis": 0.95,
            "labor_crisis": 0.60,
            "legitimacy_crisis": 0.70,
            "foreign_pressure": 0.40,
        },
        "coalition_affinities": [
            {"entity_id": "PRES", "affinity": 0.90, "condition": "any"},
            {"entity_id": "ARM", "affinity": 0.60, "condition": "security_crisis"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2011_revolution", "behavior": "escalating_crackdown_then_collapse",
             "lesson": "repression_beyond_capacity_accelerates_defection"},
            {"event": "2021_2024_arrests", "behavior": "targeted_political_opposition",
             "pattern": "selective_not_mass_repression"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2011, "event": "Security force collapse during revolution", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-05: Central Bank (BCT) ────────────────────────────────
    {
        "entity_id": "BCT",
        "actor_name": "Banque Centrale de Tunisie",
        "actor_class": "economic",
        "doctrine": "monetary_stability_under_political_constraint",
        "decision_style": "technocratic",
        "risk_tolerance": 0.20,
        "time_horizon": "medium",
        "objectives": [
            {"goal": "maintain FX reserves above 90 days import cover", "weight": 0.95, "time_horizon": "short"},
            {"goal": "control inflation below 8%", "weight": 0.85, "time_horizon": "medium"},
            {"goal": "preserve currency stability", "weight": 0.90, "time_horizon": "short"},
            {"goal": "maintain IMF program credibility", "weight": 0.80, "time_horizon": "medium"},
            {"goal": "resist political interference in monetary policy", "weight": 0.70, "time_horizon": "medium"},
        ],
        "fears": [
            {"fear": "fx_reserves_below_30_days", "threshold": 0.30, "reaction": "emergency_imf_contact + rate_hike"},
            {"fear": "currency_speculative_attack", "threshold": 0.55, "reaction": "capital_controls_signal"},
            {"fear": "political_pressure_to_print", "threshold": 0.60, "reaction": "technical_resistance + imf_signal"},
        ],
        "preferred_tools": [
            "interest_rate_adjustment", "fx_intervention",
            "liquidity_controls", "public_statements",
            "imf_technical_communication", "reserve_management",
        ],
        "input_sensitivity": {
            "fx_reserves_days": 0.99,
            "inflation_rate": 0.95,
            "imf_pressure": 0.85,
            "political_pressure": 0.70,
            "parallel_fx_premium": 0.90,
            "subsidy_fiscal_cost": 0.80,
        },
        "output_probability_matrix": {
            "rate_hike": 0.50,
            "fx_intervention": 0.60,
            "public_statement": 0.70,
            "imf_consultation": 0.65,
            "capital_controls": 0.20,
            "technical_resistance": 0.55,
        },
        "state_update_rules": [
            {"if_signal": "fx_reserves_days", "operator": "<", "threshold": 45,
             "then_action": "imf_consultation", "delta": 0.30,
             "and_action": "fx_intervention", "and_delta": 0.25},
            {"if_signal": "parallel_fx_premium", "operator": ">", "threshold": 0.25,
             "then_action": "public_statement", "delta": 0.20},
            {"if_signal": "inflation_rate", "operator": ">", "threshold": 0.10,
             "then_action": "rate_hike", "delta": 0.30},
        ],
        "authority_weights": {
            "economic_crisis": 0.95,
            "security_crisis": 0.10,
            "labor_crisis": 0.50,
            "legitimacy_crisis": 0.30,
            "foreign_pressure": 0.75,
        },
        "coalition_affinities": [
            {"entity_id": "DONOR", "affinity": 0.85, "condition": "economic_crisis"},
            {"entity_id": "PRES", "affinity": 0.40, "condition": "any"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2023_imf_negotiations", "behavior": "technical_compliance_with_political_delays"},
            {"event": "2024_reserve_stress", "behavior": "fx_rationing_informal"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2023, "event": "IMF negotiation technical compliance", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-06: Organized Opposition (LPR) ────────────────────────
    {
        "entity_id": "LPR",
        "actor_name": "Organized Opposition / Civil Coalition",
        "actor_class": "civil",
        "doctrine": "power_acquisition_through_mobilization_or_negotiation",
        "decision_style": "factional",
        "risk_tolerance": 0.55,
        "time_horizon": "medium",
        "objectives": [
            {"goal": "restore democratic institutions", "weight": 0.90, "time_horizon": "medium"},
            {"goal": "build protest coalition with UGTT", "weight": 0.80, "time_horizon": "short"},
            {"goal": "attract foreign support", "weight": 0.70, "time_horizon": "medium"},
            {"goal": "avoid violent confrontation", "weight": 0.75, "time_horizon": "short"},
            {"goal": "expose regime legitimacy failures", "weight": 0.85, "time_horizon": "short"},
        ],
        "fears": [
            {"fear": "mass_arrest_of_leadership", "threshold": 0.60, "reaction": "go_underground_or_exile"},
            {"fear": "internal_factional_split", "threshold": 0.50, "reaction": "unity_declaration"},
            {"fear": "public_apathy", "threshold": 0.65, "reaction": "narrative_escalation"},
        ],
        "preferred_tools": [
            "street_mobilization", "negotiation", "boycott",
            "foreign_appeal", "coalition_building", "media_campaign",
        ],
        "input_sensitivity": {
            "repression_index": 0.85,
            "public_anger": 0.90,
            "ugtt_posture": 0.80,
            "foreign_support": 0.70,
            "narrative_frame": 0.75,
        },
        "output_probability_matrix": {
            "street_mobilization": 0.50,
            "negotiation": 0.35,
            "boycott": 0.40,
            "foreign_appeal": 0.55,
            "coalition_building": 0.65,
            "media_campaign": 0.70,
        },
        "state_update_rules": [
            {"if_signal": "public_anger", "operator": ">", "threshold": 0.75,
             "then_action": "street_mobilization", "delta": 0.30},
            {"if_signal": "repression_index", "operator": ">", "threshold": 0.70,
             "then_action": "foreign_appeal", "delta": 0.35,
             "and_action": "street_mobilization", "and_delta": -0.20},
        ],
        "authority_weights": {
            "economic_crisis": 0.30,
            "security_crisis": 0.20,
            "labor_crisis": 0.40,
            "legitimacy_crisis": 0.80,
            "foreign_pressure": 0.50,
        },
        "coalition_affinities": [
            {"entity_id": "UGTT", "affinity": 0.70, "condition": "legitimacy_crisis"},
            {"entity_id": "ENN", "affinity": 0.80, "condition": "any"},
            {"entity_id": "PPL", "affinity": 0.60, "condition": "any"},
            {"entity_id": "LTDH", "affinity": 0.75, "condition": "any"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2013_national_dialogue", "behavior": "negotiated_under_ugtt_mediation"},
            {"event": "2021_coup", "behavior": "fragmented_response_no_unified_resistance"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2013, "event": "National dialogue participation", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-07: EU / Western Powers ──────────────────────────────
    {
        "entity_id": "EU",
        "actor_name": "European Union / Western Powers",
        "actor_class": "foreign",
        "doctrine": "stability_migration_control_over_democracy_promotion",
        "decision_style": "consensus",
        "risk_tolerance": 0.30,
        "time_horizon": "medium",
        "objectives": [
            {"goal": "prevent migration surge to Europe", "weight": 0.98, "time_horizon": "short"},
            {"goal": "maintain IMF program on track", "weight": 0.85, "time_horizon": "medium"},
            {"goal": "preserve nominal democratic norms", "weight": 0.60, "time_horizon": "medium"},
            {"goal": "counter Chinese and Russian influence", "weight": 0.70, "time_horizon": "long"},
            {"goal": "secure energy corridor stability", "weight": 0.80, "time_horizon": "medium"},
        ],
        "fears": [
            {"fear": "regime_collapse_migration_wave", "threshold": 0.65, "reaction": "emergency_aid_package"},
            {"fear": "tunisia_pivot_to_china_russia", "threshold": 0.55, "reaction": "increased_engagement_offers"},
        ],
        "preferred_tools": [
            "aid_conditionality", "diplomatic_statement", "migration_deal",
            "sanctions", "emergency_support",
        ],
        "input_sensitivity": {
            "migration_pressure": 0.99,
            "regime_stability": 0.85,
            "imf_program_status": 0.80,
            "human_rights_violations": 0.55,
            "chinese_influence": 0.70,
        },
        "output_probability_matrix": {
            "aid_conditionality": 0.65,
            "diplomatic_statement": 0.75,
            "migration_deal": 0.80,
            "sanctions": 0.10,
            "emergency_support": 0.50,
        },
        "state_update_rules": [
            {"if_signal": "migration_pressure", "operator": ">", "threshold": 0.75,
             "then_action": "emergency_support", "delta": 0.40,
             "and_action": "sanctions", "and_delta": -0.10},
            {"if_signal": "regime_stability", "operator": "<", "threshold": 0.30,
             "then_action": "aid_conditionality", "delta": 0.30},
        ],
        "authority_weights": {
            "economic_crisis": 0.70,
            "security_crisis": 0.50,
            "labor_crisis": 0.20,
            "legitimacy_crisis": 0.55,
            "foreign_pressure": 0.90,
        },
        "coalition_affinities": [
            {"entity_id": "DONOR", "affinity": 0.85, "condition": "any"},
            {"entity_id": "FRA", "affinity": 0.80, "condition": "any"},
            {"entity_id": "USA", "affinity": 0.75, "condition": "any"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2023_migration_deal", "behavior": "prioritized_migration_control_over_rights"},
            {"event": "2021_coup", "behavior": "mild_condemnation_then_continued_engagement"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2021, "event": "Post-coup continued engagement", "match": 0.0},
            {"year": 2023, "event": "Migration deal prioritization", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-08: Algeria (DZA) ─────────────────────────────────────
    {
        "entity_id": "DZA",
        "actor_name": "Algeria",
        "actor_class": "foreign",
        "doctrine": "strategic_depth_through_tunisia_stability",
        "decision_style": "centralized",
        "risk_tolerance": 0.35,
        "time_horizon": "medium",
        "objectives": [
            {"goal": "prevent Islamist spillover from Tunisia", "weight": 0.95, "time_horizon": "long"},
            {"goal": "maintain energy leverage (gas transit)", "weight": 0.85, "time_horizon": "medium"},
            {"goal": "counter NATO/French encirclement", "weight": 0.80, "time_horizon": "long"},
            {"goal": "secure border stability", "weight": 0.90, "time_horizon": "short"},
            {"goal": "preserve friendly regime in Tunis", "weight": 0.75, "time_horizon": "medium"},
        ],
        "fears": [
            {"fear": "islamist_government_in_tunisia", "threshold": 0.50, "reaction": "border_tightening + quiet_diplomacy"},
            {"fear": "nato_encirclement", "threshold": 0.60, "reaction": "russian_chinese_signaling"},
            {"fear": "tunisian_collapse_migration_wave", "threshold": 0.65, "reaction": "emergency_border_control"},
        ],
        "preferred_tools": [
            "quiet_diplomacy", "energy_leverage", "border_security_cooperation",
            "intelligence_sharing", "public_statements",
        ],
        "input_sensitivity": {
            "regime_stability": 0.90,
            "islamist_influence": 0.95,
            "migration_pressure": 0.70,
            "french_influence": 0.75,
            "energy_market": 0.60,
        },
        "output_probability_matrix": {
            "quiet_diplomacy": 0.70,
            "energy_signal": 0.40,
            "border_tightening": 0.55,
            "public_statement": 0.45,
            "intelligence_share": 0.60,
            "russian_signaling": 0.25,
        },
        "state_update_rules": [
            {"if_signal": "regime_stability", "operator": "<", "threshold": 0.35,
             "then_action": "border_tightening", "delta": 0.35,
             "and_action": "quiet_diplomacy", "and_delta": 0.15},
            {"if_signal": "islamist_influence", "operator": ">", "threshold": 0.60,
             "then_action": "intelligence_share", "delta": 0.30},
        ],
        "authority_weights": {
            "economic_crisis": 0.30,
            "security_crisis": 0.85,
            "labor_crisis": 0.20,
            "legitimacy_crisis": 0.50,
            "foreign_pressure": 0.70,
        },
        "coalition_affinities": [
            {"entity_id": "PRES", "affinity": 0.70, "condition": "any"},
            {"entity_id": "INT", "affinity": 0.65, "condition": "security_crisis"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2011_revolution", "behavior": "supported_ben_ali_then_rapidly_recognized_new_gov"},
            {"event": "2021_coup", "behavior": "maintained_engagement_with_new_presidency"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2011, "event": "Regime change rapid recognition", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-09: Business Elites (UTICA) ───────────────────────────
    {
        "entity_id": "UTICA",
        "actor_name": "UTICA — Business Elite Confederation",
        "actor_class": "economic",
        "doctrine": "profit_preservation_through_political_hedging",
        "decision_style": "consensus",
        "risk_tolerance": 0.30,
        "time_horizon": "short",
        "objectives": [
            {"goal": "protect capital from policy uncertainty", "weight": 0.95, "time_horizon": "short"},
            {"goal": "avoid capital controls", "weight": 0.90, "time_horizon": "short"},
            {"goal": "maintain access to presidency", "weight": 0.85, "time_horizon": "medium"},
            {"goal": "prevent nationalization signals", "weight": 0.80, "time_horizon": "medium"},
            {"goal": "preserve contract stability", "weight": 0.85, "time_horizon": "short"},
        ],
        "fears": [
            {"fear": "capital_controls", "threshold": 0.50, "reaction": "capital_flight_acceleration"},
            {"fear": "contract_uncertainty", "threshold": 0.60, "reaction": "lobbying_presidency"},
            {"fear": "nationalization_signal", "threshold": 0.55, "reaction": "foreign_partner_activation"},
            {"fear": "protest_disruption_of_operations", "threshold": 0.70, "reaction": "pressure_on_presidency"},
        ],
        "preferred_tools": [
            "lobbying_presidency", "capital_movement", "public_statements",
            "foreign_partner_signaling", "media_influence",
        ],
        "input_sensitivity": {
            "policy_uncertainty": 0.95,
            "protest_intensity": 0.80,
            "capital_control_risk": 0.98,
            "regime_stability": 0.75,
            "exchange_rate": 0.85,
        },
        "output_probability_matrix": {
            "lobbying": 0.75,
            "capital_flight": 0.30,
            "public_statement": 0.55,
            "foreign_appeal": 0.40,
            "hedging": 0.65,
        },
        "state_update_rules": [
            {"if_signal": "policy_uncertainty", "operator": ">", "threshold": 0.70,
             "then_action": "capital_flight", "delta": 0.35,
             "and_action": "lobbying", "and_delta": 0.15},
            {"if_signal": "protest_intensity", "operator": ">", "threshold": 0.75,
             "then_action": "public_statement", "delta": 0.25},
        ],
        "authority_weights": {
            "economic_crisis": 0.90,
            "security_crisis": 0.30,
            "labor_crisis": 0.75,
            "legitimacy_crisis": 0.40,
            "foreign_pressure": 0.50,
        },
        "coalition_affinities": [
            {"entity_id": "PRES", "affinity": 0.65, "condition": "any"},
            {"entity_id": "BCT", "affinity": 0.70, "condition": "economic_crisis"},
            {"entity_id": "DONOR", "affinity": 0.80, "condition": "any"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2011_revolution", "behavior": "hedged_early_switched_sides_at_military_neutrality"},
            {"event": "2023_imf_negotiations", "behavior": "public_support_for_reform_private_resistance"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2011, "event": "Elite side-switch during revolution", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-10: IMF / International Creditors (DONOR) ─────────────
    {
        "entity_id": "DONOR",
        "actor_name": "IMF / International Creditors",
        "actor_class": "foreign",
        "doctrine": "fiscal_discipline_as_condition_for_support",
        "decision_style": "technocratic",
        "risk_tolerance": 0.15,
        "time_horizon": "medium",
        "objectives": [
            {"goal": "ensure fiscal sustainability", "weight": 0.95, "time_horizon": "medium"},
            {"goal": "maintain program disbursement schedule", "weight": 0.80, "time_horizon": "short"},
            {"goal": "prevent sovereign default", "weight": 0.90, "time_horizon": "medium"},
            {"goal": "enforce conditionality compliance", "weight": 0.85, "time_horizon": "medium"},
            {"goal": "preserve institutional credibility", "weight": 0.70, "time_horizon": "long"},
        ],
        "fears": [
            {"fear": "program_suspension_due_to_instability", "threshold": 0.50,
             "reaction": "technical_mission_delay"},
            {"fear": "sovereign_default_contagion", "threshold": 0.65,
             "reaction": "emergency_financing_package"},
            {"fear": "reform_backsliding", "threshold": 0.40,
             "reaction": "disbursement_suspension"},
        ],
        "preferred_tools": [
            "conditionality", "disbursement_gating", "technical_missions",
            "public_statements", "program_reviews",
        ],
        "input_sensitivity": {
            "reform_implementation": 0.95,
            "fiscal_deficit": 0.90,
            "political_stability": 0.80,
            "fx_reserves": 0.85,
            "subsidy_fiscal_cost": 0.90,
        },
        "output_probability_matrix": {
            "disbursement_release": 0.50,
            "technical_mission": 0.70,
            "public_statement": 0.65,
            "conditionality_hike": 0.40,
            "program_suspension": 0.15,
            "emergency_support": 0.25,
        },
        "state_update_rules": [
            {"if_signal": "reform_implementation", "operator": "<", "threshold": 0.40,
             "then_action": "program_suspension", "delta": 0.50,
             "and_action": "disbursement_release", "and_delta": -0.45},
            {"if_signal": "fx_reserves", "operator": "<", "threshold": 0.30,
             "then_action": "emergency_support", "delta": 0.35,
             "and_action": "conditionality_hike", "and_delta": 0.20},
        ],
        "authority_weights": {
            "economic_crisis": 0.95,
            "security_crisis": 0.20,
            "labor_crisis": 0.15,
            "legitimacy_crisis": 0.40,
            "foreign_pressure": 0.80,
        },
        "coalition_affinities": [
            {"entity_id": "EU", "affinity": 0.85, "condition": "any"},
            {"entity_id": "BCT", "affinity": 0.75, "condition": "economic_crisis"},
            {"entity_id": "FRA", "affinity": 0.70, "condition": "any"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2023_2024_program", "behavior": "suspended_disbursements_pending_reform_progress"},
            {"event": "2021_coup", "behavior": "continued_technical_engagement_despite_political_shift"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2023, "event": "IMF program suspension", "match": 0.0},
        ],
        "status": "draft",
    },
    # ── PROFILE-11: Population Blocs (PPL) ────────────────────────────
    {
        "entity_id": "PPL",
        "actor_name": "Population Blocs / General Public",
        "actor_class": "civil",
        "doctrine": "survival_and_dignity",
        "decision_style": "reactive",
        "risk_tolerance": 0.50,
        "time_horizon": "short",
        "objectives": [
            {"goal": "secure affordable bread and fuel", "weight": 0.98, "time_horizon": "short"},
            {"goal": "access employment opportunities", "weight": 0.90, "time_horizon": "short"},
            {"goal": "preserve dignity and respect", "weight": 0.85, "time_horizon": "medium"},
            {"goal": "avoid police violence", "weight": 0.80, "time_horizon": "short"},
            {"goal": "emigrate if conditions worsen", "weight": 0.60, "time_horizon": "medium"},
        ],
        "fears": [
            {"fear": "bread_price_spike", "threshold": 0.65, "reaction": "street_protest"},
            {"fear": "unemployment_above_30pct", "threshold": 0.70, "reaction": "localized_unrest"},
            {"fear": "humiliation_by_security", "threshold": 0.60, "reaction": "self_immolation_or_confrontation"},
            {"fear": "hunger", "threshold": 0.75, "reaction": "looting"},
        ],
        "preferred_tools": [
            "street_protest", "self_immolation", "emigration",
            "informal_economy", "localized_unrest", "looting",
        ],
        "input_sensitivity": {
            "bread_prices": 0.99,
            "fuel_prices": 0.85,
            "unemployment_rate": 0.95,
            "repression_index": 0.70,
            "narrative_frame": 0.65,
            "remittance_flow": 0.60,
        },
        "output_probability_matrix": {
            "protest": 0.40,
            "emigration": 0.35,
            "apathetic_endurance": 0.60,
            "localized_unrest": 0.30,
            "self_immolation": 0.01,
        },
        "state_update_rules": [
            {"if_signal": "bread_prices", "operator": ">", "threshold": 0.65,
             "then_action": "protest", "delta": 0.45},
            {"if_signal": "unemployment_rate", "operator": ">", "threshold": 0.75,
             "then_action": "localized_unrest", "delta": 0.30,
             "and_action": "emigration", "and_delta": 0.20},
            {"if_signal": "repression_index", "operator": ">", "threshold": 0.80,
             "then_action": "emigration", "delta": 0.25},
        ],
        "authority_weights": {
            "economic_crisis": 0.95,
            "security_crisis": 0.30,
            "labor_crisis": 0.80,
            "legitimacy_crisis": 0.50,
            "foreign_pressure": 0.10,
        },
        "coalition_affinities": [
            {"entity_id": "UGTT", "affinity": 0.60, "condition": "labor_crisis"},
            {"entity_id": "YOUTH", "affinity": 0.85, "condition": "any"},
            {"entity_id": "LPR", "affinity": 0.50, "condition": "legitimacy_crisis"},
        ],
        "veto_conditions": [],
        "historical_patterns": [
            {"event": "2010_2011_revolution", "behavior": "self_immolation_as_activation_event",
             "trigger": "bouazizi", "activation": "bread_prices + unemployment + humiliation"},
            {"event": "2023_shortage_protests", "behavior": "localized_queue_protests"},
        ],
        "validation_score": None,
        "validated_events": [
            {"year": 2011, "event": "Revolution activation via Bouazizi", "match": 0.0},
            {"year": 2023, "event": "Bread shortage localized protests", "match": 0.0},
        ],
        "status": "draft",
    },
]
